#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'        # http://redsymbol.net/articles/unofficial-bash-strict-mode/

VERSION=$(scripts/readVersion)

# REPO_SLUG is a CI env var
PROJECT=$(sed 's/.*\///' <<< "$REPO_SLUG")

set +u
if [ -z "$SBT" ]; then
  echo "\$SBT variable is unset or empty. Please set it to be the path to a local copy of sbt before running this script."
  exit 1
fi
set -u

openssl aes-256-cbc -md sha1 -pass env:ENCRYPTION_PASSWORD -in signing-secret.pgp.enc -d | gpg --import

# plugins are published to bintray, while artifacts are published to github
if $SBT 'show sbtPlugin' | grep true; then
  "$SBT" bintrayEnsurePackageExists publish bintrayRelease
else
  "$SBT" +publish
fi

HEAD_SHA=$(git rev-parse HEAD)
TAG=v$VERSION
TAG_MSG="$PROJECT $VERSION"

TAGS_RESP=$(curl -X POST -d '{
    "tag": "'"$TAG"'",
    "object": "'"$HEAD_SHA"'",
    "message": "'"$TAG_MSG"'",
    "tagger": {
      "name": "CI",
      "email": "builds@travis-ci.com"
    },
    "type": "commit"
  }'                                             \
  -H "Content-Type: application/json"            \
  -H "Authorization: token $GITHUB_TOKEN" \
  "https://api.github.com/repos/${REPO_SLUG}/git/tags")

TAG_SHA=$(echo "$TAGS_RESP" | jq .sha)

curl -X POST -d '{
   "ref": "refs/tags/'"$TAG"'",
    "sha": '"$TAG_SHA"'
  }'                                             \
  -H "Content-Type: application/json"            \
  -H "Authorization: token $GITHUB_TOKEN" \
  "https://api.github.com/repos/${REPO_SLUG}/git/refs"
