#!/usr/bin/env ruby

require 'octokit'

if ENV['TRAVIS_PULL_REQUEST'] == "false"
  STDERR.puts 'Cannot close the current pull request on not-a-pull-request'
  exit -1
end

client = Octokit::Client.new :access_token => ENV['GITHUB_TOKEN']
client.close_pull_request ENV['TRAVIS_REPO_SLUG'], ENV['TRAVIS_PULL_REQUEST']
