#!/usr/bin/env bash

set -xeuo pipefail # STRICT MODE
IFS=$'\n\t'        # http://redsymbol.net/articles/unofficial-bash-strict-mode/

VERSION=$(sed 's/.*"\(.*\)"/\1/' version.sbt)

REPO_SLUG="$1"
PROJECT=$(sed 's/.*\///' <<< "$REPO_SLUG")

# only publish and tag on ${REPO_SLUG}#master
if [[
    "$TRAVIS_PULL_REQUEST" == "false"      &&
    "$TRAVIS_BRANCH"       == "master"     &&
    "$TRAVIS_REPO_SLUG"    == "$REPO_SLUG"
  ]] ; then
  openssl aes-256-cbc -pass pass:"$ENCRYPTION_PASSWORD" -in secring.pgp.enc -out project/local.secring.pgp -d
  openssl aes-256-cbc -pass pass:"$ENCRYPTION_PASSWORD" -in pubring.pgp.enc -out project/local.pubring.pgp -d
  openssl aes-256-cbc -pass pass:"$ENCRYPTION_PASSWORD" -in credentials.sbt.enc -out local.credentials.sbt -d

  sbt ++"$TRAVIS_SCALA_VERSION" transferPublishAndTagResources publishSigned

  # Only tag on first travis job
  if [[ "${TRAVIS_JOB_NUMBER##*.}" == "1" ]]; then
    git config --global user.email "builds@travis-ci.com"
    git config --global user.name "Travis CI"
    TAG=v$VERSION
    git tag "$TAG" -a -m "$PROJECT $VERSION"
    git push origin "$TAG"
  fi
else
  echo "Travis not running in ${REPO_SLUG}#master, so skipping publishAndTag"
fi
